name: CodeQuality

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        with:
          path: '~/.yarn'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn ci

      - run: yarn run static-code-analysis
